#!/bin/bash
echo "This a system generated information"
echo "$HOME"
echo "$HOSTNAME"
echo "$HOMEDRIVE"
echo "$USERNAME"
echo "$HOSTTYPE"
echo "$MACHTYPE"
echo "$OSTYPE"
echo "$BASH_VERSION"
echo "$BASH"
echo "$PWD"
